tenants:
  - id: default
    name: Kommunen
    contextSources:
    - endpoint: http://lolcathost:1234
      information:
      - entities:
        - idPattern: ^urn:ngsi-ld:Device:.+
          type: Device
        - idPattern: ^urn:ngsi-ld:DeviceModel:.+
          type: DeviceModel
