tenants:
  - id: default
    name: Kommunen
    contextSources:
    - endpoint: http://deviceregistry:8990
      information:
      - entities:
        - idPattern: ^urn:ngsi-ld:Device:.+
          type: Device
        - idPattern: ^urn:ngsi-ld:DeviceModel:.+
          type: DeviceModel
    - endpoint: http://orion-ld:1026
      information:
      - entities:
        - idPattern: ^urn:ngsi-ld:WaterConsumptionObserved:.+
          type: WaterConsumptionObserved
